<div class="body-content">
    <form method="POST" action="<?php //echo $this->url->getBaseUri()?>customer/update">
        <div class="row">
            <div class="col-md-6">
                <label for="first_name">Nome</label>
                <div class="input-group mb-4">
                    <div class="input-group-prepend">
                        <div class="input-group-text"><i class="fa fa-pencil"></i></div>
                    </div>
                    <?php echo $form->render('first_name', ['class' => 'form-control']); ?>
                </div>
            </div>
            <div class="col-md-6">
                <label for="last_name">Sobrenome</label>
                <div class="input-group mb-4">
                    <div class="input-group-prepend">
                        <div class="input-group-text"><i class="fa fa-pencil"></i></div>
                    </div>
                    <?php echo $form->render('last_name', ['class' => 'form-control']); ?>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <label for="username">Nome de Usuário</label>
                <div class="input-group mb-4">
                    <div class="input-group-prepend">
                        <div class="input-group-text"><i class="fa fa-user"></i></div>
                    </div>
                    <?php echo $form->render('username', ['class' => 'form-control']); ?>
                </div>
            </div>
            <div class="col-md-6">
                <label for="status_id">Status</label>
                <div class="input-group mb-4">
                    <div class="input-group-prepend">
                        <div class="input-group-text"><i class="fa fa-list"></i></div>
                    </div>
                    <?php echo $form->render('status_id', ['class' => 'form-control']); ?>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <label for="email_adress">Confirmar E-mail</label>
                <div class="input-group mb-4">
                    <div class="input-group-prepend">
                        <div class="input-group-text"><i class="fa fa-envelope"></i></div>
                    </div>
                    <?php echo $form->render('email_adress', ['class' => 'form-control']); ?>
                </div>
            </div>
            <div class="col-md-6">
                <label for="email_adress_confirm">Confirmar E-mail</label>
                <div class="input-group mb-4">
                    <div class="input-group-prepend">
                        <div class="input-group-text"><i class="fa fa-envelope"></i></div>
                    </div>
                    <?php echo $form->render('email_adress_confirm', ['class' => 'form-control']); ?>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="row">
                    <div class="col-md-6">
                        <label for="password">Senha</label>
                        <div class="input-group mb-4">
                            <div class="input-group-prepend">
                                <div class="input-group-text"><i class="fa fa-lock"></i></div>
                            </div>
                            <?php echo $form->render('password', ['class' => 'form-control']); ?>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <label for="password_confirm">Confirmar Senha</label>
                        <div class="input-group mb-4">
                            <div class="input-group-prepend">
                                <div class="input-group-text"><i class="fa fa-lock"></i></div>
                            </div>
                            <?php echo $form->render('password_confirm', ['class' => 'form-control']); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <button class="btn btn-md btn-pink" type="submit">
            <i class="fa fa-save" aria-hidden="true"></i> Salvar
        </button>
    </form>
</div>