<?php echo $this->view->partial('common/page-header'); ?>
<div class="page-content">
    <?php
    if ($this->session->has('IS_LOGIN')):
        echo $this->view->partial('common/navbar');
    endif;
    if (isset($alert)):
        ?>
        <div class="alert alert-<?php echo $alert['class']; ?>" role="alert">
            <?php echo $alert['message']; ?>
        </div>
        <?php
    endif;
    ?>    
    <!--<form method="POST" action="<?php echo $this->url->get('auth/create'); ?>">-->
    <form id="form_create" method="POST">
        <!-- Campo Hidden -->
        <?php echo $form->render('created_by_user_id'); ?>
        <?php echo $form->render('created_at'); ?>
        <div class="row">
            <div class="col-md-6">
                <label for="first_name">Nome</label>
                <div class="input-group mb-4">
                    <div class="input-group-prepend">
                        <div class="input-group-text"><i class="fa fa-pencil"></i></div>
                    </div>
                    <?php echo $form->render('first_name', ['class' => 'form-control']); ?>
                </div>
            </div>
            <div class="col-md-6">
                <label for="last_name">Sobrenome</label>
                <div class="input-group mb-4">
                    <div class="input-group-prepend">
                        <div class="input-group-text"><i class="fa fa-pencil"></i></div>
                    </div>
                    <?php echo $form->render('last_name', ['class' => 'form-control']); ?>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <label for="username">Nome de Usuário</label>
                <div class="input-group mb-4">
                    <div class="input-group-prepend">
                        <div class="input-group-text"><i class="fa fa-user"></i></div>
                    </div>
                    <?php echo $form->render('username', ['class' => 'form-control']); ?>
                </div>
            </div>
            <div class="col-md-6">
                <label for="status_id">Status</label>
                <div class="input-group mb-4">
                    <div class="input-group-prepend">
                        <div class="input-group-text"><i class="fa fa-list"></i></div>
                    </div>
                    <?php echo $form->render('status_id', ['class' => 'form-control']); ?>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <label for="email_address">E-mail</label>
                <div class="input-group mb-4">
                    <div class="input-group-prepend">
                        <div class="input-group-text"><i class="fa fa-envelope"></i></div>
                    </div>
                    <?php echo $form->render('email_address', ['class' => 'form-control']); ?>
                </div>
            </div>
            <div class="col-md-6">
                <label for="email_address_confirm">Confirmar E-mail</label>
                <div class="input-group mb-4">
                    <div class="input-group-prepend">
                        <div class="input-group-text"><i class="fa fa-envelope"></i></div>
                    </div>
                    <?php echo $form->render('email_address_confirm', ['class' => 'form-control']); ?>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="row">
                    <div class="col-md-6">
                        <label for="password">Senha</label>
                        <div class="input-group mb-4">
                            <div class="input-group-prepend">
                                <div class="input-group-text"><i class="fa fa-lock"></i></div>
                            </div>
                            <?php echo $form->render('password', ['class' => 'form-control']); ?>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <label for="password_confirm">Confirmar Senha</label>
                        <div class="input-group mb-4">
                            <div class="input-group-prepend">
                                <div class="input-group-text"><i class="fa fa-lock"></i></div>
                            </div>
                            <?php echo $form->render('password_confirm', ['class' => 'form-control']); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--<button type="submit" id="btn_save_register" class="btn btn-md btn-pink">
            <i class="fa fa-save" aria-hidden="true"></i> Salvar
        </button>-->
        <button type="button" id="btn_save_register" class="btn btn-md btn-pink">
            <i class="fa fa-save" aria-hidden="true"></i> Salvar
        </button>
        <?php
        if (!$this->session->has('IS_LOGIN')):
            ?>
            <button type="button" id="btn_cancel_register" class="btn btn-md btn-danger float-right">
                <i class="fa fa-remove" aria-hidden="true"></i> Cancelar
            </button>
            <?php
        endif;
        ?>
    </form>
</div>
<?php echo $this->view->partial('common/page-footer'); ?>