<?php echo $this->view->partial('common/page-header'); ?>
<div class="page-content">
    <?php
    echo $this->view->partial('common/navbar');
    if ($users->count() > 0):
        ?>
        <div class="table-responsive">
            <table class="table table-bordered table-striped mb-0">
                <thead class="thead-dark">
                    <tr>
                        <th class="text-uppercase">Nome</th>
                        <th class="text-uppercase">Sobrenome</th>
                        <th class="text-uppercase">Usuário</th>
                        <th class="text-uppercase">E-mail</th>
                        <th class="text-uppercase">Status</th>
                        <th class="text-uppercase">Criado Em</th>
                        <th class="text-uppercase" colspan="2">Ações</th>
                    </tr>
                </thead>
                <tbody>
                    <?php 
                    foreach ($users as $user):
                        $status = Status::findFirst($user->status_id);
                        ?>
                        <tr>
                            <td><?php echo $user->first_name; ?></td>
                            <td><?php echo $user->last_name; ?></td>
                            <td><?php echo $user->username; ?></td>
                            <td><?php echo $user->email_address; ?></td>
                            <td><?php echo $status->status_name; ?></td>
                            <td><?php echo DateLibrary::dataHoraMysqlParaDataHoraBrasileira($user->created_at); ?></td>
                            <td>
                                <button type="button" id="btn_update_register" class="btn btn-success">
                                    <i class="fa fa-edit"></i>
                                </button>
                            </td>
                            <td>
                                <a href="<?php echo $this->url->get('user/select/?cod='.$user->id); ?>" id="btn_delete_register" class="btn btn-danger">
                                    <i class="fa fa-trash-alt"></i>
                                </a>
                            </td>
                        </tr>
                        <?php 
                    endforeach; 
                    ?>
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="9">Usuários Cadastrados <span class="badge badge-danger"><?php echo $users->count(); ?></span></td>
                    </tr>
                </tfoot>
            </table>
        </div>
        <?php
    endif;
    ?>
</div>
<?php echo $this->view->partial('common/page-footer'); ?>