<?php echo $this->view->partial('common/page-header'); ?>
<div class="page-content">
    <?php
    echo $this->view->partial('common/navbar');
    if (isset($alert)):
        ?>
        <div class="alert alert-<?php echo $alert['class']; ?>" role="alert">
            <?php echo $alert['message']; ?>
        </div>
        <?php
    endif;
    if ($users->count() > 0):
        ?>
        <div class="table-responsive">
            <table class="table table-bordered table-striped mb-0" style="font-size: 14px;">
                <thead class="thead-dark">
                    <tr>
                        <th class="text-uppercase">Código</th>
                        <th class="text-uppercase">Nome</th>
                        <th class="text-uppercase">Sobrenome</th>
                        <th class="text-uppercase">Usuário</th>
                        <th class="text-uppercase">E-mail</th>
                        <th class="text-uppercase">Status</th>
                        <th class="text-uppercase">Criado Em</th>
                        <th class="text-uppercase" colspan="2">Ações</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    foreach ($users as $user):
                        $status = Status::findFirst($user->status_id);
                        if ($user->status_id != 1):
                            ?>
                            <tr>
                                <td class="cod"><?php echo $user->id; ?></td>
                                <td><?php echo $user->first_name; ?></td>
                                <td><?php echo $user->last_name; ?></td>
                                <td><?php echo $user->username; ?></td>
                                <td><?php echo $user->email_address; ?></td>
                                <td><?php echo $status->status_name; ?></td>
                                <td><?php echo DateLibrary::dataHoraMysqlParaDataHoraBrasileira($user->created_at); ?></td>
                                <td>
                                    <button type="button" id="btn_update_register" data-toggle="modal" aria-hidden="true" class="btn btn-success btn-sm">
                                        <i class="fa fa-edit"></i>
                                    </button>
                                </td>
                                <td>
                                    <button type="button" id="btn_delete_register" class="btn btn-danger btn-sm">
                                        <i class="fa fa-trash-alt"></i>
                                    </button>
                                </td>
                            </tr>
                            <?php
                        endif;
                    endforeach;
                    ?>
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="9">Usuários Cadastrados <span class="badge badge-danger"><?php echo $users->count(); ?></span></td>
                    </tr>
                </tfoot>
            </table>
        </div>
        <?php
    endif;
    ?>
</div>
<?php echo $this->view->partial('common/page-footer'); ?>