<footer class="mastfoot mt-auto">
    <a href="https://www.facebook.com/mayarasouzasobrancelhas" target="_blank">
        <img src="<?php echo $this->url->get('img/facebook.png') ?>" width="44" height="44" alt="ogotipo Facebook" class="mb-2" />
    </a>
    &nbsp;
    <a href="https://www.instagram.com/_mssobrancelhas/" target="_blank">
        <img src="<?php echo $this->url->get('img/instagram.png') ?>" width="44" height="44" alt="Logotipo Instagram" class="mb-2" />
    </a>
    <p class="text-danger">Mayara Souza Estética</p>
</footer>